lib/openssl/hmac.c: avoid conflict with stdlib hmac on NetBSD
latchset/jose pull request #130
Opened 2023-05-24 15:38 UTC by nikicoon

2023-05-24 15:39 UTC, nikicoon commented
proposal for unblocking the build on NetBSD, a lengthier version of the patch we currently use in pkgsrc.
Shorter would probably be just renaming the function, if you're okay with that.

2023-05-26 13:14 UTC, sarroutbi commented
I would prefer renaming the function, as that would help on code maintain. Otherwise, we have it duplicated for both NetBSD and non-NetBSD systems.

2023-05-26 13:16 UTC, sarroutbi requested changes
Thanks for the change.

I prefer that the existing function is renamed. That way, we don't have duplicated code, which is more difficult to mantain.

We will have a jose release in the short term and we can include this.

2023-05-26 14:05 UTC, nikicoon commented
thanks! I renamed the function to jhmac.

2023-05-26 15:00 UTC, sarroutbi approved these changes
Change LGTM. @sergio-correia : any further comment?

2023-05-26 15:01 UTC, sarroutbi approved these changes
Thanks for the PR. Change LGTM

2023-05-30 11:37 UTC, sergio-correia approved these changes

2023-05-30 12:22 UTC, merged