Display pkg_config in test logs
latchset/jose pull request #134
Opened 2023-06-02 14:20 UTC by hdholm

I don't know if this will help anyone else.  During all the pkg_config changes for PR #98 it was difficult to tell what effects changes where having. There doesn't seem to be a good way to "test" pkg_config as part of github actions (I think you'd have to install and then try and install something like tang on top of it.) But this tiny patch at least displays what pkg_config looks like so it's relatively easy to at least see what changed.

2023-06-06 10:39 UTC, sarroutbi requested changes
Thanks for the PR. As we are executing `cat` command on a file, I suggest testing the file existence before doing the `cat` command so that if the file does not exist, failure doesn't take place

2023-06-06 14:35 UTC, hdholm commented
I don't have strong feelings one way or the other, but I think there is an argument to be made that if the pkg_config file doesn't exist it should be an error worth investigating.

2024-02-06 14:26 UTC, sarroutbi approved these changes

2024-02-06 15:34 UTC, sergio-correia approved these changes

2024-02-06 15:46 UTC, merged